export const EUROPEAN_COUNTRIES = [
  { value: "Albánia", name: "Albánia" },
  { value: "Andorra", name: "Andorra" },
  { value: "Ausztria", name: "Ausztria" },
  { value: "Azerbajdzsán", name: "Azerbajdzsán" },
  { value: "Belgium", name: "Belgium" },
  { value: "Belarusz", name: "Belarusz" },
  { value: "Bosznia-Hercegovina", name: "Bosznia-Hercegovina" },
  { value: "Bulgária", name: "Bulgária" },
  { value: "Ciprus", name: "Ciprus" },
  { value: "Csehország", name: "Csehország" },
  { value: "Dánia", name: "Dánia" },
  { value: "Észtország", name: "Észtország" },
  { value: "Finnország", name: "Finnország" },
  { value: "Franciaország", name: "Franciaország" },
  { value: "Görögország", name: "Görögország" },
  { value: "Grúzia", name: "Grúzia" },
  { value: "Hollandia", name: "Hollandia" },
  { value: "Horvátország", name: "Horvátország" },
  { value: "Írország", name: "Írország" },
  { value: "Izland", name: "Izland" },
  { value: "Kazahsztán", name: "Kazahsztán" },
  { value: "Koszovó", name: "Koszovó" },
  { value: "Lengyelország", name: "Lengyelország" },
  { value: "Lettország", name: "Lettország" },
  { value: "Liechtenstein", name: "Liechtenstein" },
  { value: "Litvánia", name: "Litvánia" },
  { value: "Luxemburg", name: "Luxemburg" },
  { value: "Macedónia", name: "Macedónia" },
  { value: "Magyarország", name: "Magyarország" },
  { value: "Málta", name: "Málta" },
  { value: "Moldova", name: "Moldova" },
  { value: "Monaco", name: "Monaco" },
  { value: "Montenegró", name: "Montenegró" },
  { value: "Németország", name: "Németország" },
  { value: "Norvégia", name: "Norvégia" },
  { value: "Olaszország", name: "Olaszország" },
  { value: "Oroszország", name: "Oroszország" },
  { value: "Portugália", name: "Portugália" },
  { value: "Románia", name: "Románia" },
  { value: "San Marino", name: "San Marino" },
  { value: "Spanyolország", name: "Spanyolország" },
  { value: "Svájc", name: "Svájc" },
  { value: "Svédország", name: "Svédország" },
  { value: "Szerbia", name: "Szerbia" },
  { value: "Szlovákia", name: "Szlovákia" },
  { value: "Szlovénia", name: "Szlovénia" },
  { value: "Törökország", name: "Törökország" },
  { value: "Ukrajna", name: "Ukrajna" },
  { value: "Vatikán", name: "Vatikán" },
];

export const DEFAULT_COUNTRY = "Magyarország";
